# Generated by Django 3.2 on 2021-12-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_about_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='freelace',
            new_name='freelance',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='title',
            new_name='title1',
        ),
        migrations.AddField(
            model_name='about',
            name='title2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
