# Generated by Django 3.2 on 2021-12-17 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_about_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
    ]
