# Generated by Django 3.2 on 2021-12-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_about_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.CharField(blank=True, max_length=100)),
                ('clients', models.IntegerField(blank=True, null=True)),
                ('projects', models.IntegerField(blank=True, null=True)),
                ('support', models.IntegerField(blank=True, null=True)),
                ('awards', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
    ]
