# Generated by Django 3.2 on 2021-12-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_blogpost_category_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='profile-img.jpg', upload_to='blog'),
        ),
    ]
