# Generated by Django 3.2 on 2021-12-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='quote',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='sub_image',
            field=models.ImageField(blank=True, upload_to='blog'),
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='category',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.ManyToManyField(to='main.Category'),
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='tags',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(to='main.Tag'),
        ),
    ]
