# Generated by Django 3.2 on 2021-12-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20211218_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('client', models.CharField(blank=True, max_length=200)),
                ('project_date', models.DateField()),
                ('project_url', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('image1', models.ImageField(upload_to='portfolio')),
                ('image2', models.ImageField(upload_to='portfolio')),
                ('image3', models.ImageField(upload_to='portfolio')),
                ('category', models.ManyToManyField(to='main.Category')),
            ],
        ),
    ]
